# Generated by Django 4.0.3 on 2022-03-11 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, verbose_name='E-mail')),
                ('phone_number', models.EmailField(max_length=128, verbose_name='Phone number')),
                ('first_name', models.CharField(max_length=128, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last Name')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('Record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=128, verbose_name='Product')),
                ('Record_date', models.DateField(verbose_name='Record Date')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.patient')),
            ],
        ),
    ]
