# Generated by Django 4.0.3 on 2022-04-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='Record_date',
            new_name='record_date',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='Record_id',
            new_name='record_id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.IntegerField(max_length=128, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='record',
            name='doctor',
            field=models.CharField(max_length=128, verbose_name='Doctor'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
